Update container-security.yml

diff --git a/.github/workflows/container-security.yml b/.github/workflows/container-security.yml
--- a/.github/workflows/container-security.yml
+++ b/.github/workflows/container-security.yml
@@ -26,7 +26,7 @@ jobs:
         with:
           image-ref: 'juice-shop:latest'
           format: 'table'
-          exit-code: '1'            # Fail build if critical/high found
+         # exit-code: '1'            # Fail build if critical/high found
           vuln-type: 'os,library'   # Scan OS and app dependencies
           severity: 'HIGH,CRITICAL'
 
@@ -40,3 +40,13 @@ jobs:
         with:
           name: trivy-scan-report
           path: juice_shop/trivy-report.json
+          
+      - name: Fail build on HIGH/CRITICAL vulnerabilities
+        run: |
+          HIGH_COUNT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH" or .Severity=="CRITICAL")] | length' juice_shop/trivy-report.json)
+          if [ "$HIGH_COUNT" -gt 0 ]; then
+            echo "❌ Found $HIGH_COUNT HIGH/CRITICAL vulnerabilities. Failing the build."
+            exit 1
+          else
+            echo "✅ No HIGH/CRITICAL vulnerabilities found."
+          fi
